---
- name: copy repo
  copy: src="logstash.repo" dest=/etc/yum.repos.d/logstash.repo mode=0644

- name: install logstash
  yum: name=logstash-1.4.2 state=present

- name: Generate the SSL certificate for logstash
  shell: openssl req -x509 -batch -nodes -days 3650 -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt
  args:
    creates: /etc/pki/tls/certs/logstash-forwarder.crt
    chdir: /etc/pki/tls