---
- name: Download Java
  shell: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"
  register: result

- name: Unpack archive
  shell: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"
  when: result|success

- name: Fix ownership
  file: state=directory path={{java_name}} owner=root group=root recurse=yes

- name: Make java available for system
  shell: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2'
#  alternatives: name="java path={{java_name}}/bin/java" 

- name: Make jar available for system
  shell: 'alternatives --install "/usr/bin/jar" "jar" "{{java_name}}/bin/jar" 2'
#  alternatives: name=jar path="{{java_name}}/bin/jar" 

- name: Make javac available for system
  shell: 'alternatives --install "/usr/bin/javac" "javac" "{{java_name}}/bin/javac" 2'
#  alternatives: name=javac path="{{java_name}}/bin/javac" 

- name: Make javaws available for system
  shell: 'alternatives --install "/usr/bin/javaws" "javaws" "{{java_name}}/jre/bin/javaws" 2'
#  alternatives: name=javaws path="{{java_name}}/bin/javaws" 

- name: Clean up
  file: state=absent path="{{java_archive}}"